stages:
    - build
    - increase-version
    - deploy-baget

variables:
    PROJECT_FILE_PATH: "Wkg/Wkg/Wkg.csproj"
    MAJOR_VERSION: "7"
    MINOR_VERSION: "1"

include:
    - project: 'infrastructure/gitlab'
      ref: 'initial_templates'
      file:
          - '/gitlab/templates/jobs/build_dotnet_7.yml'
          - '/gitlab/templates/jobs/increase_version.yml'
          - '/gitlab/templates/jobs/deploy_baget_dotnet_7.yml'

build:
    extends: .build

increase-version:
    extends: .increase-version

deploy:
    extends: .deploy-baget