stages:
  - build
  - test
  - increase-version
  - deploy-baget

variables:
  PROJECT_PATH: "Wkg/Wkg"
  PROJECT_FILE_PATH: "${PROJECT_PATH}/Wkg.csproj"
  DOTNET_CI_VERSION_FILE: "${PROJECT_PATH}/WkgAssembly.cs"
  MAJOR_VERSION: "9"
  MINOR_VERSION: "0"

include:
  - project: 'wkg/gitlab-templates'
    ref: 'net-9.0'
    file:
      - '/jobs/build_dotnet_9.yml'
      - '/jobs/test_dotnet_9.yml'
      - '/jobs/increase_version.yml'
      - '/jobs/deploy_nuget_dotnet_9.yml'

build:
  extends: .build

test:
  extends: .test
  variables:
    TEST_PROJECT_FILE_PATH: "Wkg/Wkg.Tests/Wkg.Tests.csproj"

increase-version:
  extends: .increase-version
  only:
    - main
    - master
    - /^rc-.*$/
    - /^dev-.*$/ 
    - /^diag-.*$/ 

deploy:
  extends: .deploy-nuget-public