stages:
    - build
    - increase_version
    - deploy

variables:
    PROJECT_FILE_PATH: "Wkg/Wkg/Wkg.csproj"
    MAJOR_VERSION: "7"
    MINOR_VERSION: "0"

build:
    image: mcr.microsoft.com/dotnet/sdk:7.0
    script:
        - dotnet restore ${PROJECT_FILE_PATH}
        - dotnet build ${PROJECT_FILE_PATH} -c Release -o app/build
    stage: build
    tags:
        - docker   

increase_version:
    variables:
        VERSION: "${MAJOR_VERSION}.${MINOR_VERSION}.${CI_PIPELINE_ID}"
    script:
        - mkdir vars
        - case ${CI_COMMIT_BRANCH} in 
            (rc-*) export VERSION=${VERSION}"-rc";; 
            (dev-*) export VERSION=${VERSION}"-dev";;  
            esac        
        - echo $VERSION > vars/version
        - echo "New Version Number is ${VERSION}"
    stage:
        increase_version
    only:
        # Deprecated, use rules with newer gitlab version
        - main
        - /^rc-.*$/
        - /^dev-.*$/ 
    artifacts:
        paths: 
            - vars
    tags:
        - docker    

deploy:
    image: mcr.microsoft.com/dotnet/sdk:7.0 
    script:
        - cat ${WKG_ROOT_CA} >> /usr/local/share/ca-certificates/wkgrootca.crt
        - update-ca-certificates --fresh
        - cat vars/version
        - export VERSION=$(cat vars/version) 
        - echo ${VERSION}
        - dotnet pack "${PROJECT_FILE_PATH}" -v q -c Release -o app/pack -p:PackageVersion=${VERSION} -p:IsPackable=true
        # Todo Case when debug or rc or always?
        - dotnet pack "${PROJECT_FILE_PATH}" -v q -c Release -o app/pack -p:PackageVersion=${VERSION} -p:IsPackable=true -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg
        - dotnet nuget add source http://wkg-spiwie.home.wkg.de:5555/v3/index.json --name baget
        - dotnet nuget push "app/pack/*.nupkg" --source baget -k ${BAGET_API_KEY}
        - dotnet nuget push "app/pack/*.snupkg" --source baget -k ${BAGET_API_KEY}
    stage:
        deploy
    dependencies:
        - increase_version  
    only:
        # Deprecated, use rules with newer gitlab version
        - main
        - /^rc-.*$/
        - /^dev-.*$/  
    artifacts:
        name: pack-output
        paths:
            - app/pack
        expire_in: 2 hour              
    tags:
        - docker