//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wkg {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wkg.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A workload was scheduled, but it was already completed. What are you doing?.
        /// </summary>
        internal static string ThreadingWorkloads_QdiscEnqueueFailed_AlreadyCompleted {
            get {
                return ResourceManager.GetString("ThreadingWorkloads_QdiscEnqueueFailed_AlreadyCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A workload was scheduled, but no workload scheduler was found in the current context. This is a bug in the qdisc implementation..
        /// </summary>
        internal static string ThreadingWorkloads_QdiscEnqueueFailed_NoScheduler {
            get {
                return ResourceManager.GetString("ThreadingWorkloads_QdiscEnqueueFailed_NoScheduler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A workload was scheduled, but could not be bound to the qdisc. This is a likely a bug in the qdisc scheduler implementation..
        /// </summary>
        internal static string ThreadingWorkloads_QdiscEnqueueFailed_NotBound {
            get {
                return ResourceManager.GetString("ThreadingWorkloads_QdiscEnqueueFailed_NotBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A workload scheduler was already set for this qdisc. This is a bug in the qdisc implementation..
        /// </summary>
        internal static string ThreadingWorkloads_QdiscInitializationFailed_AlreadyBound {
            get {
                return ResourceManager.GetString("ThreadingWorkloads_QdiscInitializationFailed_AlreadyBound", resourceCulture);
            }
        }
    }
}
